config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resources :users do
        get 'me', on: :collection
      end

      get '/me' => "credentials#me"
    end
  end

  resources :phones do
    collection do
      get 'verify'
      post 'verify'
      post 'create_code'
      post 'submit_code'
      post 'create_password_code'
      post 'password_code'
    end
  end

  resources :addresses

  resources :stores

  resources :solutionists

  resources :workers

  resources :customers

  resources :orders

  resources :finances

  get 'main/index'

  devise_for :users, :controllers => {registrations: "registrations", sessions: 'sessions'}

  resources :users do
    get :search, on: :collection
    get :edit_password, on: :collection
    put :update_password
    put :forbidden
  end

  root 'users#index'

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get 'sign_up', to: "registrations#new"
    get 'sign_out', to: "devise/sessions#destroy"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    can :manage, User do |u|
      u.id == user.id
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
end

app/models/admin.rb
class Admin < User
end

app/models/customer.rb
class Customer < User
  has_many :addresses, as: :addressable
end

app/models/front_desker.rb
class FrontDesker < User
end

app/models/manager.rb
class Manager < User
end

app/models/order.rb
class Order < User
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base

  validates :phone, format: { with: /\A1\d{10}\z/ }, presence: true

  # def self.create_code(phone)
  #   self.create!(phone: phone, verify_code: 1111)
  # end

  def validate!
    if Time.now - self.created_at < 1800
      self.update_attribute(:verified, true)
    end
  end

  def send_message_code
    require 'submail'
    message_config = {}
    message_config["appid"] = "10102"
    message_config["appkey"] = "dd33372eba6c478d665a9f7dd8ab052b"
    message_config["signtype"] = "md5"
    messagexsend = MessageXSend.new(message_config)
    messagexsend.set_project("0AtoR3")

    loop do
      messagexsend.add_to(self.phone)
      self.verify_code = SecureRandom.random_number.to_s[-5..-1]
      messagexsend.add_var("code", self.verify_code)
      result = JSON.parse(messagexsend.message_xsend())
      result['status'] == 'success' and break
    end
  end
end

app/models/solutionist.rb
class Solutionist < User
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :users
  has_many :manager
  has_many :customers
  has_many :front_deskers

  has_many :addresses, as: :addressable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :authentication_keys => [:phone]  

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "girl.svg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def admin?
    type == 'Admin'
  end

  def show_gender
    gender ? "男" : "女"
  end

  def show_source
    source.zero? ? "Web" : "App"
  end

end

app/models/worker.rb
class Worker < User
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  skip_before_action :authenticate_user!
  before_action :doorkeeper_authorize!
  before_action :reject_forbidden_user
  
  respond_to :json

  def show
    respond_with current_user
  end

  def me
    respond_with current_user
  end

  def index
    respond_with @users = User.all
  end

  # PUT    /users/:id(.:format)                         users#update
  def update
    @user = User.find(params[:id])
    @user.update_attributes!(user_params)
    render :json => @user
  end

  def create
    response.headers['X-CSRF-Token'] = form_authenticity_token
    if User.where(phone: user_params[:phone]).exists?
      render :json => "user with phone #{user_params[:phone]} already exists"
    else
      @user = User.create!(
        user_params.merge(
          source: user_source,
          email: "#{user_params[:phone]}@jinguwen.com"
        )
      )
      respond_with @user, location: nil
    end
  end

  private

    def reject_forbidden_user
      if current_user.try(:forbidden)
        render :json => "user account forbidden", status: 401
      end
    end 

    def user_params
      params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation, :source)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  before_action :redirect_back, except: [:edit_password, :update_password]
  skip_before_action :authenticate_user!, only: [:edit_password, :update_password]

  def index
    @users = User.order('created_at desc').paginate(:page => params[:page], :per_page => 30)
  end

  def edit
  end

  def forbidden
    @user = User.find(params[:user_id])
    @user.update_attributes!(forbidden: params[:forbidden])
    redirect_to :back, notice: "更新成功!"
  end

  def update_password
    @user = User.find(params[:user_id])
    @user.update_attributes(user_params)
    if @user.valid?
      sign_in @user
      redirect_to :back, notice: "密码更新成功"
    else
      redirect_to :back, notice: @user.errors.messages.values.flatten.join
    end
  end

  def edit_password
    pm = PhoneNumber.where(phone: params[:phone], verify_code: params[:code]).last
    if pm.validate!
      @user = User.where(phone: params[:phone]).first
    else
      redirect :back, alert("验证码错误")
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes!(user_params)
    redirect_to :back, notice: "用户信息更新成功"
  end

  def search
    @users = User.order('created_at desc').where(
      "name like ? or email like ?", "%#{params[:q]}%", "%#{params[:q]}%"
    ).paginate(:page => params[:page], :per_page => 30)
  end

  def show
    respond_with @user
  end

  private

  def redirect_back
    (current_user.try(:admin?) || can?(:manage, @user)) or redirect_to main_index_path
  end

  def user_params
    if current_user.try(:admin?)
      params.require(:admin).permit(:phone, :password, :password_confirmation, :name, :avatar, :forbidden)
    else
      params.require(:user).permit(:phone, :password, :password_confirmation, :name, :avatar, :forbidden)
    end
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/users/_list.html.slim
- if @users.blank?
  .well
    h4 没有搜索到相关用户
- else
  table.table.table-bordered
    thead
      tr
        th
          | 注册时间
        th
          | 来源 
        th
          | Id
        th
          | 姓名
        th
          | 电话
        th
          | 邮箱
        th
          | 禁止登陆
    tbody
      - @users.each_with_index do |user, i|
        tr class="#{%w(success danger warning info)[i%4]}"
          td= user.created_at.strftime("%Y-%m-%d %H:%M")
          td= user.show_source
          td= user.id
          td= user.name
          td= user.phone
          td= user.email
          - if user.forbidden
            td= link_to "取消", user_forbidden_path(user, forbidden: false), method: :put
          - else
            td= link_to "禁止", user_forbidden_path(user, forbidden: true), method: :put
  = will_paginate(@users)

app/views/users/edit.html.slim
.main-content ng-controller="UsersController as users"
  #content ng-init='value=true'
    .user-info-block.well.center-block[ng-view]
       = simple_form_for(@user, url: user_path(@user)) do |f|
         .form-inputs
           = f.input :name, required: true, label: "昵称", placeholder: "昵称"
           = f.input :phone, required: true, label: "电话", placeholder: "电话号码", input_html: { disabled: true, style: 'color: #333' }
           .form-group style='display:none'
             = f.input :avatar, input_html: { style: 'width: 80%;float: left' }, label_html: { style: "width: 20%; float: left" }

           .form-group
             .inline-label.col-md-2
               label class="file optional control-label" for="user_avatar"
                 abbr title="required"
                  | *
                 | 头像
             .inline-input.col-md-10
               input class="file optional form-control" type="file" name="user[avatar]" id="user_avatar"

         .form-actions.text-center
           = f.button :submit, value: "更新用户信息", :style => 'margin-top: 20px'

app/views/users/edit_password.html.slim
.main-content ng-controller="UsersController as users"
  #content ng-init='value=true'
    .user-info-block.well.center-block[ng-view]
       = simple_form_for(@user, url: user_update_password_path(@user), html: { method: :put }) do |f|
         .form-inputs
           = f.input :password, autocomplete: "off", required: true, label: "新密码"
           = f.input :password_confirmation, required: true
         .form-actions.text-center
           = f.button :submit, value: "更新密码", :style => 'margin-top: 20px'

app/views/users/index.html.slim
= render 'list'

app/views/users/search.html.slim
= render 'list'

app/views/users/show.html.slim
.main-content
  #sidebar
    ul.nav.nav-list.nav-list-vivid
      li
        = link_to '#'
          div
            span.fui-windows.glyph
            span.text 历史订单
      li.active
        = link_to user_path(current_user)
          div
            span.fui-user.glyph
            span.text 个人信息
      li
        = link_to '#edit/1'
          div
            span.fui-photo.glyph
            span.text 上传头像
      li
        = link_to edit_user_password_path
          div
            span.fui-lock.glyph
            span.text 修改密码
      li
        = link_to '#'
          div
            span.fui-mail.glyph
            span.text 邮件通知
  #content.page class="{{pageClass}}" ng-view=''
  #sidebar-resizer resizer="vertical" resizer-width="2" resizer-left="#sidebar" resizer-right="#content" resizer-max="400"