config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resources :users do
        get 'me', on: :collection
      end

      get '/me' => "credentials#me"
    end
  end

  resources :phones do
    collection do
      get 'verify'
      post 'verify'
      post 'create_code'
      post 'submit_code'
      post 'create_password_code'
      post 'password_code'
    end
  end

  resources :addresses

  resources :stores

  resources :solutionists

  resources :workers

  resources :customers

  resources :orders

  resources :finances

  get 'main/index'

  devise_for :users, :controllers => {registrations: "registrations", sessions: 'sessions'}

  resources :users do
    get :search, on: :collection
    get :edit_password, on: :collection
    put :update_password
    put :forbidden
  end

  root 'users#index'

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get 'sign_up', to: "registrations#new"
    get 'sign_out', to: "devise/sessions#destroy"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    can :manage, User do |u|
      u.id == user.id
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
end

app/models/admin.rb
class Admin < User
end

app/models/customer.rb
class Customer < User
  has_many :addresses, as: :addressable
end

app/models/front_desker.rb
class FrontDesker < User
end

app/models/manager.rb
class Manager < User
end

app/models/order.rb
class Order < User
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base

  validates :phone, format: { with: /\A1\d{10}\z/ }, presence: true

  # def self.create_code(phone)
  #   self.create!(phone: phone, verify_code: 1111)
  # end

  def validate!
    if Time.now - self.created_at < 1800
      self.update_attribute(:verified, true)
    end
  end

  def send_message_code
    require 'submail'
    message_config = {}
    message_config["appid"] = "10102"
    message_config["appkey"] = "dd33372eba6c478d665a9f7dd8ab052b"
    message_config["signtype"] = "md5"
    messagexsend = MessageXSend.new(message_config)
    messagexsend.set_project("0AtoR3")

    loop do
      messagexsend.add_to(self.phone)
      self.verify_code = SecureRandom.random_number.to_s[-5..-1]
      messagexsend.add_var("code", self.verify_code)
      result = JSON.parse(messagexsend.message_xsend())
      result['status'] == 'success' and break
    end
  end
end

app/models/solutionist.rb
class Solutionist < User
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :users
  has_many :manager
  has_many :customers
  has_many :front_deskers

  has_many :addresses, as: :addressable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :authentication_keys => [:phone]  

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "girl.svg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def admin?
    type == 'Admin'
  end

  def show_gender
    gender ? "男" : "女"
  end

  def show_source
    source.zero? ? "Web" : "App"
  end

end

app/models/worker.rb
class Worker < User
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @addresses = Address.all
    respond_with(@addresses)
  end

  def show
    respond_with(@address)
  end

  def new
    @address = Address.new
    respond_with(@address)
  end

  def edit
  end

  def create
    @address = Address.new(address_params)
    @address.save
    respond_with(@address)
  end

  def update
    @address.update(address_params)
    respond_with(@address)
  end

  def destroy
    @address.destroy
    respond_with(@address)
  end

  private
    def set_address
      @address = Address.find(params[:id])
    end

    def address_params
      params.require(:address).permit(:addressable_type, :country, :province, :city, :district, :details)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/addresses/_form.html.slim
= simple_form_for(@address) do |f|
  = f.error_notification

  .form-inputs
    = f.input :addressable_type
    = f.input :country
    = f.input :province
    = f.input :city
    = f.input :district
    = f.input :details

  .form-actions
    = f.button :submit

app/views/addresses/edit.html.slim
h1 Editing address

== render 'form'

= link_to 'Show', @address
'|
= link_to 'Back', addresses_path

app/views/addresses/index.html.slim
h1 Listing addresses

table
  thead
    tr
      th Addressable type
      th Country
      th Province
      th City
      th District
      th Details
      th
      th
      th

  tbody
    - @addresses.each do |address|
      tr
        td = address.addressable_type
        td = address.country
        td = address.province
        td = address.city
        td = address.district
        td = address.details
        td = link_to 'Show', address
        td = link_to 'Edit', edit_address_path(address)
        td = link_to 'Destroy', address, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Address', new_address_path

app/views/addresses/new.html.slim
h1 New address

== render 'form'

= link_to 'Back', addresses_path

app/views/addresses/show.html.slim
p#notice = notice

p
  strong Addressable type:
  = @address.addressable_type
p
  strong Country:
  = @address.country
p
  strong Province:
  = @address.province
p
  strong City:
  = @address.city
p
  strong District:
  = @address.district
p
  strong Details:
  = @address.details

= link_to 'Edit', edit_address_path(@address)
'|
= link_to 'Back', addresses_path