config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resources :users do
        get 'me', on: :collection
      end

      get '/me' => "credentials#me"
    end
  end

  resources :phones do
    collection do
      get 'verify'
      post 'verify'
      post 'create_code'
      post 'submit_code'
      post 'create_password_code'
      post 'password_code'
    end
  end

  resources :addresses

  resources :stores

  resources :solutionists

  resources :workers

  resources :customers

  resources :orders

  resources :finances

  get 'main/index'

  devise_for :users, :controllers => {registrations: "registrations", sessions: 'sessions'}

  resources :users do
    get :search, on: :collection
    get :edit_password, on: :collection
    put :update_password
    put :forbidden
  end

  root 'users#index'

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get 'sign_up', to: "registrations#new"
    get 'sign_out', to: "devise/sessions#destroy"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    can :manage, User do |u|
      u.id == user.id
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
end

app/models/admin.rb
class Admin < User
end

app/models/customer.rb
class Customer < User
  has_many :addresses, as: :addressable
end

app/models/front_desker.rb
class FrontDesker < User
end

app/models/manager.rb
class Manager < User
end

app/models/order.rb
class Order < User
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base

  validates :phone, format: { with: /\A1\d{10}\z/ }, presence: true

  # def self.create_code(phone)
  #   self.create!(phone: phone, verify_code: 1111)
  # end

  def validate!
    if Time.now - self.created_at < 1800
      self.update_attribute(:verified, true)
    end
  end

  def send_message_code
    require 'submail'
    message_config = {}
    message_config["appid"] = "10102"
    message_config["appkey"] = "dd33372eba6c478d665a9f7dd8ab052b"
    message_config["signtype"] = "md5"
    messagexsend = MessageXSend.new(message_config)
    messagexsend.set_project("0AtoR3")

    loop do
      messagexsend.add_to(self.phone)
      self.verify_code = SecureRandom.random_number.to_s[-5..-1]
      messagexsend.add_var("code", self.verify_code)
      result = JSON.parse(messagexsend.message_xsend())
      result['status'] == 'success' and break
    end
  end
end

app/models/solutionist.rb
class Solutionist < User
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :users
  has_many :manager
  has_many :customers
  has_many :front_deskers

  has_many :addresses, as: :addressable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :authentication_keys => [:phone]  

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "girl.svg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def admin?
    type == 'Admin'
  end

  def show_gender
    gender ? "男" : "女"
  end

  def show_source
    source.zero? ? "Web" : "App"
  end

end

app/models/worker.rb
class Worker < User
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | 金顾问
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag "application", 'app', controller_name
    = csrf_meta_tags
  body
    .nav.navbar.navbar-fixed-top.navbar-default.navbar-lg.top-nav-bar.large role="navigation"
      .navbar-header
        = link_to image_tag('logo-h.jpg', size: '190x55'), root_path, class: 'navbar-brand'
      #navbar-collapse-01.collapse.navbar-collapse
        ul.nav.navbar-nav.cl-effect-17
          - if current_user.try(:admin?)
            li class=active_class('users')
              = link_to "用户", users_path
        - if current_user
          .dropdown.pull-right.navbar-dropdown
            .navbar-avatar.btn.btn-warning
              = user_link(current_user, size: '50x50')
              strong.mlx= current_user.name

            ul.dropdown-menu#dropdown-menu[role="menu"]
              li= link_to edit_user_path(current_user) do
                div
                  /span.fui-user.glyph
                  span.text  个人信息
              li= link_to edit_user_registration_path do
                div
                  /span.fui-gear.glyph
                  span.text  修改密码
              li.divider
              li= link_to sign_out_path do
                div
                  /span.fui-power.glyph
                  span.text  退出该账号
        /form.navbar-form.navbar-right[action=search_users_path role="search"]
          .form-group
            .input-group
              input#navbarInput-01.form-control[type="search" placeholder="输入用户姓名或邮箱搜索" name='q']
              span.input-group-btn
                button.btn[type="submit"]
                  span.fui-search
    - unless flash.blank?
      div class="alert alert-success text-center"
        /button class="close fui-cross" data-dismiss="alert"
        button class="close" data-dismiss="alert"
          | x
        strong
          - flash.each do |k, msg|
            = msg
        
    .body-container
      = yield
    = render 'shares/footer'

app/views/layouts/devise.html.slim
doctype html
html  ng-app='baozheng'
  head
    title
      | 金顾问
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application', 'app'
    = csrf_meta_tags
  body.devise
    .body-container
      - unless flash.blank?
        div class="alert alert-success text-center" style='margin-top: -78px'
          /button class="close fui-cross" data-dismiss="alert"
          button class="close" data-dismiss="alert"
            | x
          strong
            - flash.each do |k, msg|
              = msg
      .content.center-block.row
        .left.text-center.col-md-4
          = link_to image_tag('logo.jpg', size: '150x150', class: 'pulse'), root_path
        .right.well.col-md-8
          = yield
    = render 'shares/footer'

app/views/shares/_footer.html.slim
.bottom-menu
  .container
    .row
      .col-md-2.col-sm-2
        /= image_tag 'flat/bag.svg', size: '45x45', style: 'margin-top: -10px;opacity: 0.7'
        /= image_tag 'logo-brand.png', size: '96x45', style: 'margin-top: -10px;opacity: 0.6'
      .col-md-8.col-sm-8
        ul.bottom-menu-list
          li= link_to '关于我们', '#'
          li= link_to '联系我们', '#'
          li= link_to '服务条款', '#'
          li= link_to '隐私条款', '#'
          li= link_to '加入我们', '#'
      .col-md-2.col-sm-2 ng-init="wechat=false"
        /.bottom-menu-iconic-list
          .left.pull-right
            li ng-mouseover='wechat=true' ng-mouseleave='wechat=false'
              = link_to image_tag('wechat_icon.png'), '#'
          .right.pull-right
            li= link_to image_tag('weibo_icon.png'), 'http://www.weibo.com/u/3304382227', target: '_blank', title: '点击关注包拯官方微博', class: 'has-tooltip'
      /.wechat-qrcode.animate-pulse ng-if="wechat"
        = image_tag 'qrcode.png', size: '150x150'

/javascript:
  $(document).on("scroll",function(){
    if($(document).scrollTop()>0){ 
      $(".top-nav-bar").removeClass("navbar-lg").addClass("navbar-sm");
      }
    else{
      $(".top-nav-bar").removeClass("navbar-sm").addClass("navbar-lg");
      }
    });

app/views/shares/dynamic_sidebar.html.slim
#home.container
  .header
    a.menu-icon[href="#"]
      i.fui-list-columned
    ul.side-menu
      h2.title
        | Menu
      li.link
        a[href="#"]
          | Google
      li.link
        a[href="#"]
          | Twitter
      li.link
        a[href="#"]
          | Facebook
      li.link
        a[href="#"]
          | GitHub
      li.link
        a[href="#"]
          | Reddit
      li.link
        a[href="#"]
          | Tumblr

app/views/shares/footer.html.slim
.bottom-menu
  .container
    .row
      .col-md-2.col-sm-2
        = image_tag 'flat/bag.svg', size: '45x45', style: 'margin-top: -10px;opacity: 0.7'
      .col-md-8.col-sm-8
        ul.bottom-menu-list
          li= link_to '关于我们', '#'
          li= link_to '联系我们', '#'
          li= link_to '服务条款', '#'
          li= link_to '隐私条款', '#'
          li= link_to '加入我们', '#'
      .col-md-2.col-sm-2
        .bottom-menu-iconic-list
          li= link_to content_tag(:span, '', class: 'fui-facebook').html_safe, '#'
          li= link_to content_tag(:span, '', class: 'fui-twitter').html_safe, '#'
/javascript:
  $(document).on("scroll",function(){
    if($(document).scrollTop()>0){ 
      $(".top-nav-bar").removeClass("navbar-lg").addClass("navbar-sm");
      }
    else{
      $(".top-nav-bar").removeClass("navbar-sm").addClass("navbar-lg");
      }
    });